name: This is my first workflows
on:
    push:
        branches:
            - main  

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: print message           
              run: echo "Hello, World!"

        